### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by llamahunter** [fabianishere/pam_reattach#6]
This extension and pam_tid seem to have stopped working on Big Sur. Did Apple change something? Do I need to configure something differently?  I am using iTerm, which previously required map_reattach.so to work correctly.

**Comment by fabianishere** [comment]
Could you check whether your PAM config is still correct? You need to reconfigure PAM after every system upgrade.

**Comment by llamahunter** [comment]
Yup. Have to reapply after every os upgrade. I have a spare copy that I cp into place every time. Used to work. Seems to have stopped, tho.

**Comment by llamahunter** [comment]
```
% cat /etc/pam.d/sudo
# sudo: auth account password session
auth       optional       pam_reattach.so
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
```

**Comment by llamahunter** [comment]
```
%  ls -al /usr/local/lib/pam/pam_reattach.so* /usr/lib/pam/pam_tid.so*
-r--r--r--  1 root   wheel  215264 Jan  1  2020 /usr/lib/pam/pam_tid.so.2
-r--r--r--  1 rdlee  admin   17952 Oct 22  2019 /usr/local/lib/pam/pam_reattach.so
```

**Comment by fabianishere** [comment]
This is the output I get for the second command:
```
ls -al /usr/local/lib/pam/pam_reattach.so* /usr/lib/pam/pam_tid.so*
-r--r--r--  1 root    wheel  215264 Jan  1  2020 /usr/lib/pam/pam_tid.so.2
lrwxr-xr-x  1 fabian  staff      53 Mar  5 10:25 /usr/local/lib/pam/pam_reattach.so -> ../../Cellar/pam_reattach/1.2/lib/pam/pam_reattach.so
```

Did you install this module via Homebrew or did you build it manually?  Also, are you by any chance running on M1?

**Comment by llamahunter** [comment]
> This is the output I get for the second command:
> 
> ```
> ls -al /usr/local/lib/pam/pam_reattach.so* /usr/lib/pam/pam_tid.so*
> -r--r--r--  1 root    wheel  215264 Jan  1  2020 /usr/lib/pam/pam_tid.so.2
> lrwxr-xr-x  1 fabian  staff      53 Mar  5 10:25 /usr/local/lib/pam/pam_reattach.so -> ../../Cellar/pam_reattach/1.2/lib/pam/pam_reattach.so
> ```
> 
> Did you install this module via Homebrew or did you build it manually? 

Hmm... pretty sure I installed via homebrew, but maybe I copied it from somewhere trying to 'fix' things? Brew thinks it's installed

```
% brew list pam_reattach
/usr/local/Cellar/pam_reattach/1.2/include/reattach.h
/usr/local/Cellar/pam_reattach/1.2/lib/pam/pam_reattach.so
/usr/local/Cellar/pam_reattach/1.2/lib/libreattach.a
/usr/local/Cellar/pam_reattach/1.2/share/man/ (2 files)
```

> Also, are you by any chance running on M1?

I wish!  No, I have a 2016 MBP.

Let me try removing the entry from /usr/local/lib/pam and forcing reinstall from brew.

**Comment by llamahunter** [comment]
Hmm... still no symlink, but after doing `brew reinstall pam_reattach`, I diffed the files in Cellar and /usr/local/lib/pam, and they are the same. Still doesn't work. Mysterious.

**Comment by fabianishere** [comment]
Interesting...

Could you share the version of Big Sur and iTerm2 you are running as well as the steps you use to reproduce the problem. I am unable to reproduce the issue at this moment unfortunately.

**Comment by llamahunter** [comment]
MacOS 11.15.1 (tho also with 11.15)
ITerm2 3.4.8

To reproduce problem, run `sudo ls` and expect the TID dialog to come up.  Instead, it does not come up. 

Hmm.. I tried with Terminal, too, and it also didn't work. I don't think Terminal needs the pam_reattach trick that iTerm2 does. Maybe there's something else wrong.

**Comment by llamahunter** [comment]
Argh... pilot error.  Somehow, my fingerprints got erased from my secure enclave (not sure how that happened. haven't replaced motherboard or reinstalled OS or anything). Everything works after adding them back.
